config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :ratings
  resources :posts do
    resources :ratings
    resources :comments
  end
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer
#
# Indexes
#
#  index_comments_on_post_id  (post_id)
#

class Comment < ApplicationRecord
  belongs_to :post
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id                   :integer          not null, primary key
#  description          :string
#  name                 :string
#  picture_content_type :string
#  picture_file_name    :string
#  picture_file_size    :bigint
#  picture_updated_at   :datetime
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  post_id              :integer
#
# Indexes
#
#  index_items_on_post_id  (post_id)
#

class Item < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  has_many :comments
  has_many :ratings
  has_many :items
  validates :title, presence: true

  def self.search(title)
    if title
      where('title LIKE ?', "%#{title}%")
    else
      all
    end
  end

  def mean_rating

  end
end

app/models/rating.rb
# == Schema Information
#
# Table name: ratings
#
#  id         :integer          not null, primary key
#  score      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer
#
# Indexes
#
#  index_ratings_on_post_id  (post_id)
#

class Rating < ApplicationRecord
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @post.comments.create! comments_params
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comments_params
    params.required(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.search(params[:title])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new()

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_post

  def create
    @post.ratings.create! ratings_params
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def ratings_params
    params.required(:rating).permit(:score)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/comments/_comment.html.erb
<p><%=comment.body %> <%= comment.created_at.to_s(:long) %></p>

app/views/comments/_new.html.erb
<%= form_for([@post, Comment.new], remote:true) do |form| %>
  Your comment:<br>
  <%= form.text_area :body, size: '50x20' %><br>
  <%= form.submit %>
<% end %>

app/views/home/index.html.erb
<h1>
  Home Page
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Super Blog", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
        </ul>
      </div>
    </div>
  </nav>
  <div class="container main-container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :body, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :body, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @post, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing post</h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="page-header">
  <%= link_to new_post_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Post
  <% end %>
  <h1>Posts</h1>
  <div>
    <%= form_tag(posts_path, method: :get) do %>
      Search Title <%= text_field_tag :title, params[:title] %>
      <%= submit_tag 'Search', name: nil %>
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Body</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <%= content_tag :tr, id: dom_id(post), class: dom_class(post) do %>
                      <td><%= post.title %></td>
                      <td><%= post.body %></td>
                    <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New post</h1>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_post_path(@post), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show post</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @post.title %></dd>

  <dt>Body:</dt>
  <dd><%= @post.body %></dd>

  <dt>Number of Ratings:</dt>
  <dd><%= @post.ratings.count %></dd>
  <%= render 'ratings/new', post: @post %>

  <dt>Average Rating:</dt>
  <dd><%= @post.mean_rating %></dd>

  <br><br>
  <div><%= bar_chart @post.ratings.group(:score).count %></div>


  <h2>Comments</h2>

    <div id="comments">
      <%= render @post.comments %>
    </div>

    <%=render 'comments/new', post: @post %>

</dl>

app/views/ratings/_new.html.erb
<%= form_for([@post, Rating.new]) do |form| %>
    Rating: <%= number_field(:rating, :score, in: 1..5, step: 1) %>
    <%= form.submit %>
<% end %>